### ISSUE TITLE
Plot name has problems with less-than sign <

### ISSUE THREAD

**Issue by B-Hartmann** [DC-analysis/DCscope#82] opened 2021-03-19 08:15 UTC
When using the less-than sign "<" in the plot name, the string is not shown correctly in the plot window, it gets clipped directly before the "<". The plot window shows the complete name, though, it's just the string within the window.
No problems with the greater-than sign ">".

ShapeOut 2.6.0
![Bug_plot_name_shapeOut2](https://user-images.githubusercontent.com/75362246/111750401-7afe7a80-8893-11eb-9042-0905074402c8.PNG)

**Comment by paulmueller** [comment] 2021-03-19 08:37
Interesting. This looks like a pyqtgraph issue and should be fixed upstream. Will create an issue there when I have time. In the mean time, you could use "≤".

**Comment by paulmueller** [comment] 2021-04-29 21:38
Upstream issue: https://github.com/pyqtgraph/pyqtgraph/issues/1750

**Comment by paulmueller** [comment] 2021-04-30 09:07
Turns out this is not a bug, but a feature. Pyqtgraph interprets those strings as html. I will disable this in the next release.

**Closed as completed** 2021-04-30 09:07 UTC
Labels: bug
