### ISSUE TITLE
Graphs not same size

### ISSUE THREAD

**Issue by marketakub** [DC-analysis/DCscope#63] opened 2020-11-30 11:14 UTC
![image](https://user-images.githubusercontent.com/46028267/100603570-94d87980-3305-11eb-840c-d7f5a9415bb6.png)

**Comment by paulmueller** [comment] 2020-11-30 11:54
possibly a duplicate of #33

**Comment by paulmueller** [comment] 2021-02-23 15:10
Closing, because this is a duplicate.

**Closed as completed by paulmueller** 2021-02-23 15:10 UTC
Labels: duplicate
