### ISSUE TITLE
Failure at startup

### ISSUE THREAD

**Issue by matteounimib** [DC-analysis/DCscope#145] opened 2023-10-19 21:29 UTC
>> pipx install shapeout2
>> .local/bin/shapeout2
It open a windows with the following error.

Unhandled exception in Shape-Out version 2.13.6:
Traceback (most recent call last):
  File "/home/me/.local/bin/shapeout2", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/me/.local/pipx/venvs/shapeout2/lib/python3.11/site-packages/shapeout2/__main__.py", line 35, in main
    window = ShapeOut2(*app.arguments()[1:])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.local/pipx/venvs/shapeout2/lib/python3.11/site-packages/shapeout2/gui/main.py", line 88, in __init__
    dclab.rtdc_dataset.fmt_dcor.APIHandler.add_api_key(api_key)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'dclab.rtdc_dataset.fmt_dcor' has no attribute 'APIHandler'

**Comment by paulmueller** [comment] 2023-10-20 08:54
Hi, this is due to a regression dclab. An intermediate solution is to downgrade dclab to a version below 0.53.0

`pipx install shapeout2 "dclab<0.53.0"`

**Comment by paulmueller** [comment] 2023-10-20 08:55
This bug is already fixed in the `master` branch.

**Comment by paulmueller** [comment] 2023-10-24 20:32
This is fixed in Shape-Out 2.13.7

**Closed as completed by paulmueller** 2023-10-24 20:32 UTC
